"""update subtitle schema

Revision ID: 157754974d7c
Revises: 45530560c479
Create Date: 2026-06-03 18:35:33.631162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '157754974d7c'
down_revision: Union[str, Sequence[str], None] = '45530560c479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'projects', ['id'])
    op.create_unique_constraint(None, 'subscriptions', ['id'])
    op.add_column('subtitle_entries', sa.Column('error_message', sa.Text(), nullable=True))
    op.create_index('idx_subtitle_translation_status', 'subtitle_entries', ['subtitle_file_id', 'translation_status'], unique=False)
    op.create_unique_constraint(None, 'subtitle_entries', ['id'])
    op.add_column('subtitle_files', sa.Column('source_language', sa.String(), nullable=False))
    op.add_column('subtitle_files', sa.Column('target_language', sa.String(), nullable=False))
    op.add_column('subtitle_files', sa.Column('total_entries', sa.Integer(), nullable=False))
    op.add_column('subtitle_files', sa.Column('translated_entries', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'subtitle_files', ['id'])
    op.create_unique_constraint(None, 'translation_cache', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'translation_cache', type_='unique')
    op.drop_constraint(None, 'subtitle_files', type_='unique')
    op.drop_column('subtitle_files', 'translated_entries')
    op.drop_column('subtitle_files', 'total_entries')
    op.drop_column('subtitle_files', 'target_language')
    op.drop_column('subtitle_files', 'source_language')
    op.drop_constraint(None, 'subtitle_entries', type_='unique')
    op.drop_index('idx_subtitle_translation_status', table_name='subtitle_entries')
    op.drop_column('subtitle_entries', 'error_message')
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_constraint(None, 'projects', type_='unique')
    # ### end Alembic commands ###
